### ISSUE TITLE
[🚀 Feature]: Update .NET service classes

### ISSUE THREAD

**Issue by titusfortner** [SeleniumHQ/selenium#12273]
### Feature and motivation

Java, Ruby & Python have all implemented various features for Service classes that can not be done in .NET right now.

- [x] Firefox can not be set to log to file ➡️ #16081 
- [x] No driver can be set to log to the console. ➡️ #16097
- [x] Chrome/Edge can not set log level (in Service class) ➡️ #16098
- [x] Chrome/Edge can not set `readableTimeStamp` ➡️ #16133
- [x] Firefox can not set truncated logs or profile root ➡️ #16131
- [x] ~~Safari can not enable logging~~ 

### Usage example

            var service = EdgeDriverService.CreateDefaultService();
            service.LogToConsole = true
            service.LogLevel = ChromiumDriverLogLevel.Debug 

            driver = new EdgeDriver(service);

**Comment by diemol** [comment]
I struck out Safari logs because I did not see any output while trying it out.

**Comment by diemol** [comment]
All PRs got merged. Closing this.
