### ISSUE TITLE
[🚀 Feature]: Better compatibility with Appium in Python

### ISSUE THREAD

**Issue by p0deje** [SeleniumHQ/selenium#13959]
### Feature and motivation

Separate issue to track Python work for #13946
cc @KazuCocoa 

### TODO
- [ ] Support overriding default locator conversion
  - https://github.com/SeleniumHQ/selenium/blob/9f8e0b849783f2386b92363e5b23e73c3c08c963/py/selenium/webdriver/remote/webdriver.py#L731-L739
  - https://github.com/appium/python-client/blob/a9af896bc08735e2927c8ace90be2e420b09ce5e/appium/webdriver/webelement.py#L99-L112
- [ ] Support using custom element classes
  - https://github.com/appium/python-client/blob/a9af896bc08735e2927c8ace90be2e420b09ce5e/appium/webdriver/webdriver.py#L420-L432
- [ ] Support overriding User-Agent in HTTP client (see below for example)
- [ ] Support registering extra headers in HTTP client (see below for example)
- [ ] Support ignore certificates
  - https://github.com/appium/python-client/blob/a9af896bc08735e2927c8ace90be2e420b09ce5e/appium/webdriver/appium_connection.py#L52-L54
- [ ] Support registering custom finders for SearchContext
  - https://github.com/appium/python-client/blob/a9af896bc08735e2927c8ace90be2e420b09ce5e/appium/webdriver/common/appiumby.py
- [ ] Support registering extra HTTP commands and methods on the driver
  - https://github.com/appium/python-client/blob/master/appium/webdriver/extensions/screen_record.py
